'use client'

import {
  IWallet,
  WalletContext,
  WalletContextProvider,
} from '@/contexts/wallet-context'
import './globals.css'
import { Inter } from 'next/font/google'
import { FC, PropsWithChildren, use, useContext } from 'react'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default RootLayout
